env:
  global:
    - secure: "KsKPPU4TwOYB59HsvlRswBgvwENNC4xDjpQQHTKbgdcci+ESBtrVQ2PA8fvExqwQNedXGeWQOhYGekTYzNESS1yjYWHQ4N88wL76WuWj+1KHSLK+/JoVfqw93kdCazTjbDHhLK9ZFHf8MDO0KGbdRguSw8hdeGrsfjBLej8SZsQ="

language: cpp

compiler:
  - clang
  - gcc
  
sudo: required
dist: trusty

script:
  - ./configure --taglib
  - make -j`grep processor /proc/cpuinfo | wc -l`
  
addons:
  apt:
    packages:
    - libqt4-dev
    - qt4-qmake
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - zip
    - libx11-dev
    - libtag1-dev
  coverity_scan:
    project:
      name: "nulloy/nulloy"
      description: "Build submitted via Travis CI"
    notification_email: sergey@vlasov.me
    build_command_prepend: "./configure --taglib --no-gstreamer"
    build_command: "make -j`grep processor /proc/cpuinfo | wc -l`"
    branch_pattern: coverity_scan
