language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository ppa:gstreamer-developers/ppa -y
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev zip libx11-dev libtag1-dev
  - sudo apt-get install fluxbox
  - sudo apt-get install python-pip
  - pip install --user cpp-coveralls

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - fluxbox &

script:
  - CXXFLAGS="--coverage -g -O0" LDFLAGS="-lgcov --coverage" ./configure --taglib --tests
  - make -j`grep processor /proc/cpuinfo | wc -l`
  - ./test
  
after_success:
  - ~/.local/bin/coveralls --exclude lib --exclude tests --gcov-options '\-lp'
